### ISSUE TITLE
What specific elevation does 'zs' refer to in the code?

### ISSUE THREAD

**Issue by chenming2023** [Ulises-ICM-UPC/UBathy#1]
This file can be obtained using the [UBasic](https://github.com/Ulises-ICM-UPC/UBasic) software. In the same directory should also exist the file <anyname>zs.txt with the position of the water surface during the recording of the video with the following structure:

<anyname>zs.txt: One line with
z-coordinate-free-surface

**Comment by Ulises-ICM-UPC** [comment]
zs is the mean sea level corresponding to the video, using the same datum as that for the GCPs. Thanks for your interest

**Comment by chenming2023** [comment]
I got it, thank you very much for your reply

**Comment by Ulises-ICM-UPC** [comment]
Great!
